### ISSUE TITLE
use @arguments and @argumentsDefinitions

### ISSUE THREAD

**Issue by sibelius** [entria/ReactNavigationRelayModern#16]

**Comment by ssomnoremac** [comment]
Is there a breaking change on Relay 1.4 around this?
I can't get an nearly identical `UserList.js` to work. I get this as the error. It's not all too clear

```
{"name":"RelayNetwork","type":"mustfix","framesToPop":2,"source":{"operation":{"fragment":{"argumentDefinitions":
[{"kind":"LocalArgument","name":"count","type":"Int!","defaultValue":null}],"kind":"Fragment","metadata":null,"name":"ShiftListQuery","selections":
[{"kind":"FragmentSpread","name":"ShiftList_query","args":null}],"type":"RootQueryType"},"id":null,"kind":"Batch","metadata":{},"name":"ShiftListQuery","query":{"argumentDefinitions":
[{"kind":"LocalArgument","name":"count","type":"Int!","defaultValue":null}],"kind":"Root","name":"ShiftListQuery","operation":"query","selections":[{"kind":"LinkedField","alias":null,"args": ...
```

**Comment by sibelius** [comment]
try to check this post https://medium.com/@sibelius/relay-modern-argumentdefinitions-d53769dbb95d

and this one https://medium.com/@andreicalazans/relay-is-just-getting-better-54112ffc1a9e

**Comment by ssomnoremac** [comment]
thanks, I actually realized that Relay expects or accounts for "data" as the root field of the fetch query response. I was doing `response.json().data`. I'll try to get a PR for this issue soon.

**Comment by ssomnoremac** [comment]
@sibelius , using `@argumentDeinfitions` in my app now and introduced a new arg
```
@argumentDefinitions(
  count: { type: "Int" },
  cursor: { type: "String" },
  employerId: { type: "ID!" }) {...
```

Relay compiler won't compile unless I pass a default even though I'm clearly passing the id here:
```
export default createQueryRenderer(
  EmployerOpeningListPaginationContainer,
  EmployerOpeningList, 
  {
    variables: {cursor: null, count: 10, employerId: 1 },
    query
  }
);
```
`ERROR:
RelayCompilerScope: No value found for required argument `$employerId: ID!`.`
and... I added employerId to `onRefresh` and `onEndReached` refreshVariables
still no luck
any ideas?

**Comment by sibelius** [comment]
you need to use @arguments as well

@argumentDefinition will create local variables

employerId in your queryRenderer is a global one

`...EmployerOpeningList_query @arguments(employerId: $employerId)`

**Comment by ssomnoremac** [comment]
ok, nevermind, got it working with adding the arg to the outside query. Yup, you just said it. I still don't understand the global / local thing. Need to stare at this one file... for even longer :0

**Comment by sibelius** [comment]
we can improve this later on
