### ISSUE TITLE
How does one prepare data for SectionList?

### ISSUE THREAD

**Issue by ssomnoremac** [entria/ReactNavigationRelayModern#23]
I can't resolve how to use RelayModern for RN `SectionList`. In other words, where do I prepare data like this
```
  [{name: "Event1", day: "Tuesday"},
  {name: "Event2", day: "Tuesday"},
  {name: "Event3", day: "Wednesday"}, ...]
```
to look like this:
```
[{data: [...], key: "Tuesday"},
 {data: [...], key: "Wednesday"},...]
```
Surely not in the render function. That doesn't seem performant. Isn't this what `prepareVariables` used to allow for? Where is that functionality in RelayModern?

**Comment by sibelius** [comment]
On render is good enough

Or u could try to improve this doing a setState on componentWillReceiveProps

**Comment by sibelius** [comment]
prepareVariables was for input, on Modern you should be explicit for this computed prepared variables

**Comment by ssomnoremac** [comment]
Oh yeah, it was for input, I remember now. Yeah, I will try it for a while in render and see how performance is. It just didn't seem ideal to load more on scroll and have it re-sort every time but perhaps it really isn't an issue.

**Comment by ssomnoremac** [comment]
@sibelius thanks for getting back about it!
